# -*- coding: utf-8 -*-
"""cardio.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1L9mAgd1GM08LZjEQb9vyH3P1kIB5bvkO
"""

!git clone https://github.com/MaxSoloAT/cardio_pd.git

# Імпорт бібліотек.
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
sns.set();

df = pd.read_csv('./cardio_pd/cardio_train.csv', sep=';') # Завантаження інформації з csv.

df.head(10).T # Візуалізація інформації у вигляді таблиці.

df.describe().T # Статистика по кожному числовому признаку.

df['cardio'].value_counts() # Кількість здорових та хворих.

df['cardio'].value_counts(normalize=True) # Те саме що і зверху але у %.

"""**Візуалізація** "*ФІЧ*""""

df['height'].hist(); # Розподіл значень зросту пацієнтів. Теорія стверджує, що зростання - величина, зазвичай має нормальний розподіл.

df['height'].hist(bins=20); # Покращена статистика

sns.boxplot(df['height']);
# Ширина "ящика" дорівнює інтерквантільному розмаху (різниця між третім Q3 і першим Q1 квартилями).
# Вертикальна лінія всередині ящика показує медіану (другий квартиль).
# "Вусики" обмежують точки, що потрапляють в інтервал [Q1-1.5 * IQR; Q3 + 1.5 * IQR], де IQR - інтерквартільний розмах.
# Нарешті, окремі точки на графіку відповідають викидам - нетиповим для даної вибірки значень. Як бачимо, їх виявилося досить багато.

df['age'] = (df['age'] / 365).round()

df.groupby('cardio')['age'].mean()

df.groupby('cardio')['age'].mean().plot(kind='bar') 
plt.ylabel('Age')
plt.show();

plt.figure(figsize=(15, 8)) 
sns.countplot(y='age', hue='cardio', data=df);
# Кількість здорових і хворих пацієнтів за віковими групами.

plt.scatter(df['age'], df['height']);
# Окремі значення в даних - це просто помилки введення.

sns.jointplot(x='height', y='weight', data=df);
# Помилки і аномалії в даних чітко видно і на цьому графіку. 
# Також можна зробити висновок, що без урахування похибок зріст і вага мають розподіл, близький до нормального.